# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 * * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Git
        run: |
          git config --global user.name "Techie Tina the Snarky Circuit"
          git config --global user.email "techanv-bot@users.noreply.github.com"
        
      - name: Delete existing github-metrics.svg
        run: rm -f github-metrics.svg

      - uses: lowlighter/metrics@latest
        id: generate-metrics
        with:
          token: ${{ secrets.GH_PAT }}

          # Options
          user: techanv-bot
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
          plugin_code: yes
          plugin_code_languages: javascript, typescript, rust
          plugin_code_load: 400
          plugin_gists: yes
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 14
          commits_authoring: Techie Tina the Snarky Circuit, techanv-bot, techanv-bot@users.noreply.github.com
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://techanv.com
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 1
          plugin_stackoverflow_sections: answers-top
          plugin_stackoverflow_limit: 2
          plugin_traffic: yes

      - name: Move generated file to github-metrics.svg
        run: mv metrics.svg github-metrics.svg

      - name: Commit changes
        run: |
          git add github-metrics.svg
          git commit -m "Update github-metrics.svg - [Skip techanv-bot]" --author="Techie Tina the Snarky Circuit <techanv-bot@users.noreply.github.com>"
          git push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
